steps:
# Build the maven war file and push the image to container registry
- name: 'maven'
  entrypoint: 'mvn'
  args: ['clean', 'package', 'com.google.cloud.tools:jib-maven-plugin:2.8.0:build', '-Dimage: gcr.io/${_Project}/cloudsqlrun:v1', '-DskipTests']
# Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'run-sql', '--image', 'gcr.io/${_Project}/cloudsqlrun:v1', '--region', 'us-central1', '--allow-unauthenticated', '--add-cloudsql-instances', '${_cloudsql-instances}', '--set-env-vars', 'INSTANCE_UNIX_SOCKET: ${_INSTANCE_UNIX_SOCKET}', '--set-env-vars', 'INSTANCE_CONNECTION_NAME: ${_INSTANCE_CONNECTION_NAME}', '--set-env-vars', 'DB_NAME: ${_DB_NAME}', '--set-env-vars', 'DB_USER: ${_DB_USER}', '--set-env-vars', 'DB_PASS: ${_DB_PASS}']
substitutions:
  _Project: gcp-certs-387105
  _cloudsql-instances: gcp-certs-387105:us-central1:cloudrun-db-instance
  _INSTANCE_UNIX_SOCKET: /cloudsql/gcp-certs-387105:us-central1:cloudrun-db-instance
  _INSTANCE_CONNECTION_NAME: gcp-certs-387105:us-central1:cloudrun-db-instance
  _DB_NAME: compare_db
  _DB_USER: cloud-user
  _DB_PASS: Gcp@2022
  